import { buildProductManagementSimulation, type ProductManagementSimulationSpec } from './pmSimulationBuilder';

const payLoopSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-001',
    name: 'Improve First Transaction Completion',
    companyName: 'PayLoop',
    industry: 'Fintech',
    productDescription: 'a mobile wallet for students, freelancers, NYSC members, and young professionals',
    targetUsers: 'Students, NYSC members, freelancers, first-time digital banking users, and young professionals',
    businessGoal: 'Increase first transaction completion from new users',
    mainProductProblem: 'Users sign up but do not complete their first transfer, bill payment, or wallet funding',
    keyMetric: 'First transaction completion rate',
    stakeholderContext: [
        'Head of Product wants to understand why users drop off after registration.',
        'Customer Support says users are confused by verification steps and account limits.',
        'Growth wants faster activation because acquisition spend is rising.',
        'Engineering has two weeks for an MVP improvement.',
        'Compliance says KYC cannot be removed, but it can be explained better.',
    ],
    selectedMvpFeature: 'Onboarding Checklist',
    selectedMvpReason: 'It gives new users one clear place to see required setup steps, pending blockers, and the next action before making a first transaction.',
    finalPortfolioOutcome: 'Improving First Transaction Completion for PayLoop',
    difficulty: 'intro',
    primaryColor: '#0f9f6e',
    budget: 120000,
    fundingStatus: 'Seed stage',
    employees: '35',
    headquarters: 'Lagos, Nigeria',
    technicalStack: 'React Native, Node.js, PostgreSQL, bank transfer APIs, KYC provider integration',
    marketContext: 'Digital wallets compete on trust, speed, and successful first-use onboarding for young Nigerian users.',
    existingFlow: ['Signup', 'Verify identity', 'Fund wallet', 'Send money or pay a bill'],
    analytics: [
        'Last 30 days: 18,400 new signups from referrals and campus campaigns.',
        'KYC started by 64% of new users, but completed by only 38%.',
        'Wallet funding started by 29% of signups and completed by 17%.',
        'First transaction completion rate is 22%; target is 40%.',
        'Support tickets tagged "cannot send money" increased 31% week over week.',
    ],
    userFeedback: [
        '"I signed up, but I did not know what to do next."',
        '"The app asked me for BVN and I did not understand why."',
        '"I wanted to send money, but it said my account was limited."',
        '"I added my details, but I was not sure if my account was ready."',
        '"I tried to fund my wallet but got confused about which option to use."',
    ],
    supportTickets: [
        'Ticket 1942: User asks why transfer button is disabled after account creation.',
        'Ticket 2001: User says "account limited" message does not explain what step is missing.',
        'Ticket 2018: User asks if BVN is mandatory before sending money.',
        'Ticket 2033: User funded wallet but did not know whether verification was complete.',
        'Ticket 2050: User abandoned after seeing KYC prompt twice.',
    ],
    stakeholderMemo: [
        'From: Head of Product',
        'We are acquiring users, but too many are inactive after signup. Please investigate the activation drop-off and recommend one simple MVP change that can help a new user complete their first transaction faster.',
    ],
    internalNotes: [
        'Growth: Referral campaigns are working, but many signups never become active users.',
        'Support: Most new-user tickets are about verification, account limits, and next steps.',
        'Engineering: A two-week MVP can include UI changes and messaging, but not a full KYC provider rebuild.',
        'Compliance: KYC and transaction limits must remain in place.',
    ],
    featureIdeas: [
        { idea: 'Onboarding checklist', problemSolved: 'Users know what steps remain before they can transact.' },
        { idea: 'KYC explanation screen', problemSolved: 'Users understand why BVN and identity checks are required.' },
        { idea: 'Progress bar', problemSolved: 'Users see how close they are to account readiness.' },
        { idea: 'First transaction guide', problemSolved: 'Users are guided to fund wallet or send money after setup.' },
        { idea: 'Clear account limit message', problemSolved: 'Users understand what is blocking a transfer.' },
    ],
    impactMapExamples: [
        { userProblem: 'Confusing verification process', businessImpact: 'Users stop before making a first transaction', metricAffected: 'Activation rate' },
        { userProblem: 'No clear next step after signup', businessImpact: 'Users abandon the wallet before reaching value', metricAffected: 'First transaction completion rate' },
        { userProblem: 'Unclear account limit message', businessImpact: 'Users lose trust and contact support', metricAffected: 'Transaction success satisfaction' },
    ],
    stakeholders: [
        { id: 'hop', name: 'Amina Bello', role: 'Head of Product', department: 'Product', influence: 10, satisfaction: 62, communicationStyle: 'direct', concerns: ['activation drop-off', 'MVP clarity'], priorities: ['first transaction completion'] },
        { id: 'growth', name: 'Tunde Adeyemi', role: 'Growth Lead', department: 'Growth', influence: 8, satisfaction: 55, communicationStyle: 'analytical', concerns: ['acquisition cost', 'inactive signups'], priorities: ['activation speed'] },
        { id: 'support', name: 'Ifeoma Okeke', role: 'Customer Support Lead', department: 'Support', influence: 7, satisfaction: 52, communicationStyle: 'collaborative', concerns: ['repetitive tickets', 'unclear account states'], priorities: ['ticket reduction'] },
        { id: 'eng', name: 'David Mensah', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 64, communicationStyle: 'analytical', concerns: ['two-week MVP scope'], priorities: ['simple implementation'] },
        { id: 'compliance', name: 'Halima Sani', role: 'Compliance Lead', department: 'Compliance', influence: 9, satisfaction: 70, communicationStyle: 'formal', concerns: ['KYC requirements', 'transaction limits'], priorities: ['regulatory safety'] },
    ],
    risks: [
        { id: 'risk-kyc-confusion', title: 'Users may abandon because KYC still feels risky or unclear', severity: 'high', likelihood: 'high' },
        { id: 'risk-scope', title: 'MVP could become too broad for two weeks', severity: 'medium', likelihood: 'medium' },
        { id: 'risk-compliance-copy', title: 'Copy must not imply KYC is optional', severity: 'high', likelihood: 'medium' },
    ],
    kpis: [
        { id: 'activation', label: 'First Transaction Completion', value: 22, maxValue: 100, status: 'critical', goal: 'Reach 40%', progress: 22 },
        { id: 'kyc', label: 'KYC Completion', value: 38, maxValue: 100, status: 'warning', goal: 'Reach 55%', progress: 38 },
        { id: 'funding', label: 'Wallet Funding Completion', value: 17, maxValue: 100, status: 'critical', goal: 'Reach 30%', progress: 17 },
        { id: 'tickets', label: 'New User Support Load', value: 68, maxValue: 100, status: 'warning', goal: 'Reduce by 20%', progress: 68 },
    ],
};

const veriCashSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-002',
    name: 'Improve KYC Completion',
    companyName: 'VeriCash',
    industry: 'Fintech',
    productDescription: 'a mobile wallet that requires identity verification before higher transaction limits unlock',
    targetUsers: 'First-time digital wallet users, students, young professionals, and freelancers',
    businessGoal: 'Increase verified users while staying compliant',
    mainProductProblem: 'Users create accounts but abandon verification before completing BVN, ID upload, or selfie checks',
    keyMetric: 'KYC completion rate',
    stakeholderContext: [
        'Product wants more verified users because unverified accounts cannot use core wallet features fully.',
        'Compliance says the verification steps are mandatory and cannot be removed.',
        'Support receives repeated questions about why BVN, ID, and selfie verification are needed.',
        'Engineering can improve screens, progress states, and save-and-continue behavior for MVP.',
    ],
    selectedMvpFeature: 'KYC Education and Progress Screen',
    selectedMvpReason: 'It explains why each verification step exists and shows users how many steps remain without weakening compliance requirements.',
    finalPortfolioOutcome: 'Improving KYC Completion for VeriCash',
    difficulty: 'intro',
    primaryColor: '#2563eb',
    budget: 100000,
    fundingStatus: 'Pre-Series A',
    employees: '42',
    headquarters: 'Abuja, Nigeria',
    technicalStack: 'React Native, Node.js, PostgreSQL, KYC provider SDK, secure document storage',
    marketContext: 'Fintech onboarding requires a balance between compliance, trust, and clear user education.',
    existingFlow: ['Signup', 'Enter BVN', 'Upload ID', 'Take selfie', 'Verification result'],
    analytics: [
        'Last 30 days: 14,200 account creations.',
        'KYC start rate is 58%, but completion rate is 34%.',
        'Drop-off is highest on BVN explanation screen and ID upload screen.',
        '19% of failed KYC users return within seven days.',
        'Verified users are 2.7x more likely to fund wallet than unverified users.',
    ],
    userFeedback: [
        '"Why do you need my BVN? I got scared and closed the app."',
        '"I started verification but did not know how many steps were left."',
        '"The selfie failed and I did not know what to fix."',
        '"I do not want to upload my ID if I do not understand who can see it."',
        '"I was busy and wanted to continue later but could not find where I stopped."',
    ],
    supportTickets: [
        'Ticket 882: User asks if BVN is safe to submit.',
        'Ticket 910: User asks whether ID upload is compulsory.',
        'Ticket 944: User says selfie failed three times with no clear instruction.',
        'Ticket 967: User asks how to continue incomplete verification.',
        'Ticket 990: User wants to know why transaction limit is low after signup.',
    ],
    stakeholderMemo: [
        'From: Compliance and Product',
        'We cannot remove required identity verification steps. Please investigate why users abandon KYC and propose a product improvement that increases completion while keeping the flow compliant.',
    ],
    internalNotes: [
        'Compliance: BVN, ID, and selfie steps are required for risk controls.',
        'Support: Privacy fear and unclear failed-verification guidance create many tickets.',
        'Engineering: Save-and-continue is possible, but provider-level changes are out of scope for MVP.',
        'Product: Verified users have much higher activation and retention.',
    ],
    featureIdeas: [
        { idea: 'KYC explanation screen', problemSolved: 'Users understand why verification is needed.' },
        { idea: 'Verification progress bar', problemSolved: 'Users know how many steps remain.' },
        { idea: 'Privacy reassurance copy', problemSolved: 'Users feel safer submitting sensitive data.' },
        { idea: 'Save and continue later', problemSolved: 'Users can return to incomplete KYC.' },
        { idea: 'Failed verification guidance', problemSolved: 'Users know how to fix rejected details.' },
    ],
    impactMapExamples: [
        { userProblem: 'Users do not trust BVN request', businessImpact: 'Users abandon KYC and remain unverified', metricAffected: 'KYC completion rate' },
        { userProblem: 'Users cannot see remaining steps', businessImpact: 'Users perceive the process as long and quit', metricAffected: 'Verification completion rate' },
        { userProblem: 'Failed selfie guidance is unclear', businessImpact: 'Users contact support or churn after rejection', metricAffected: 'Support ticket volume' },
    ],
    stakeholders: [
        { id: 'product', name: 'Nora Ibrahim', role: 'Product Lead', department: 'Product', influence: 10, satisfaction: 60, communicationStyle: 'direct', concerns: ['verified user growth'], priorities: ['KYC completion'] },
        { id: 'compliance', name: 'Bisi Lawal', role: 'Compliance Manager', department: 'Compliance', influence: 10, satisfaction: 72, communicationStyle: 'formal', concerns: ['identity requirements', 'privacy language'], priorities: ['regulatory adherence'] },
        { id: 'support', name: 'Kelvin Ojo', role: 'Support Lead', department: 'Support', influence: 7, satisfaction: 50, communicationStyle: 'collaborative', concerns: ['repetitive KYC questions'], priorities: ['self-service clarity'] },
        { id: 'eng', name: 'Grace Etuk', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 64, communicationStyle: 'analytical', concerns: ['provider constraints'], priorities: ['low-risk UI changes'] },
    ],
    risks: [
        { id: 'risk-privacy', title: 'Poor privacy copy could reduce trust further', severity: 'high', likelihood: 'medium' },
        { id: 'risk-compliance', title: 'Product copy might accidentally weaken compliance framing', severity: 'critical', likelihood: 'low' },
        { id: 'risk-provider', title: 'KYC provider errors may remain outside product team control', severity: 'medium', likelihood: 'medium' },
    ],
    kpis: [
        { id: 'kyc-completion', label: 'KYC Completion', value: 34, maxValue: 100, status: 'critical', goal: 'Reach 50%', progress: 34 },
        { id: 'kyc-start', label: 'KYC Start Rate', value: 58, maxValue: 100, status: 'warning', goal: 'Reach 70%', progress: 58 },
        { id: 'verified-funding', label: 'Verified User Funding', value: 42, maxValue: 100, status: 'warning', goal: 'Reach 60%', progress: 42 },
        { id: 'support', label: 'KYC Support Tickets', value: 74, maxValue: 100, status: 'critical', goal: 'Reduce by 25%', progress: 74 },
    ],
};

const swiftPaySpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-003',
    name: 'Reduce Failed Transfer Complaints',
    companyName: 'SwiftPay',
    industry: 'Fintech',
    productDescription: 'a digital wallet for bank transfers, wallet transfers, airtime, and bill payments',
    targetUsers: 'Young professionals, freelancers, small merchants, and everyday wallet users',
    businessGoal: 'Reduce support complaints and increase trust in transfers',
    mainProductProblem: 'Users experience failed or delayed transfers and do not understand what happened to their money',
    keyMetric: 'Transfer success satisfaction score',
    stakeholderContext: [
        'Support is overwhelmed by failed transfer and pending transfer tickets.',
        'Operations says failures often come from bank downtime, provider delays, and wrong account validation.',
        'Product wants a self-service experience that explains transfer status clearly.',
        'Engineering can expose transfer state and status messaging, but cannot control every bank provider outage.',
    ],
    selectedMvpFeature: 'Transfer Status Tracker',
    selectedMvpReason: 'It shows users whether their transfer is processing, failed, reversed, or successful, reducing uncertainty and support escalation.',
    finalPortfolioOutcome: 'Reducing Failed Transfer Complaints for SwiftPay',
    difficulty: 'intermediate',
    primaryColor: '#7c3aed',
    budget: 150000,
    fundingStatus: 'Series A',
    employees: '65',
    headquarters: 'Lagos, Nigeria',
    technicalStack: 'React Native, Node.js, payment processor APIs, banking integrations, event logging',
    marketContext: 'In payments, trust depends on users knowing what is happening to their money during failures and delays.',
    existingFlow: ['Enter recipient', 'Confirm amount', 'Send transfer', 'Processing', 'Receipt or failure message'],
    analytics: [
        'Last 30 days: 420,000 transfer attempts.',
        'Transfer success rate is 91.2%, but satisfaction score is 61/100.',
        '7.4% of transfers show pending for more than five minutes.',
        'Support receives 6,800 transfer-related tickets per month.',
        'Repeat transfer attempts after a pending state occur in 11% of affected sessions.',
    ],
    userFeedback: [
        '"My transfer said pending for hours and I did not know if my money was gone."',
        '"The app just said failed. It did not tell me why."',
        '"I sent money twice because I was not sure the first one worked."',
        '"Support took too long to explain what happened."',
        '"I need proof that the money will reverse if it fails."',
    ],
    supportTickets: [
        'Ticket 3301: User asks if pending transfer means money is lost.',
        'Ticket 3312: User repeated a transfer and wants one payment reversed.',
        'Ticket 3340: User asks why bank transfer failed after debit.',
        'Ticket 3366: User requests proof for recipient because receipt is unclear.',
        'Ticket 3391: User asks when failed transfer refund will arrive.',
    ],
    stakeholderMemo: [
        'From: Support Lead',
        'The top driver of tickets is transfer uncertainty. We need users to understand what is happening before they contact an agent. Please propose a simple product improvement that reduces failed transfer complaints and protects trust.',
    ],
    internalNotes: [
        'Operations: Most pending states are provider delays, not permanent failures.',
        'Support: Users need refund timelines, failure reasons, and escalation paths.',
        'Engineering: We can show transaction event states already stored in logs.',
        'Product: Avoid encouraging duplicate transfers when one is already pending.',
    ],
    featureIdeas: [
        { idea: 'Transfer status tracker', problemSolved: 'Users know what is happening to their money.' },
        { idea: 'Clear failed transfer reason', problemSolved: 'Users understand why the transfer failed.' },
        { idea: 'Refund timeline message', problemSolved: 'Users know when money should return.' },
        { idea: 'Duplicate transfer warning', problemSolved: 'Users avoid sending the same money twice.' },
        { idea: 'Support escalation button', problemSolved: 'Users can report unresolved cases faster.' },
    ],
    impactMapExamples: [
        { userProblem: 'Pending status is unclear', businessImpact: 'Users contact support and lose trust', metricAffected: 'Transfer success satisfaction score' },
        { userProblem: 'Failure reason is not explained', businessImpact: 'Users assume the platform is unreliable', metricAffected: 'Repeat transfer rate' },
        { userProblem: 'No refund timeline', businessImpact: 'Users panic and create multiple tickets', metricAffected: 'Support ticket volume' },
    ],
    stakeholders: [
        { id: 'product', name: 'Maya Okafor', role: 'Product Manager', department: 'Product', influence: 9, satisfaction: 57, communicationStyle: 'collaborative', concerns: ['trust', 'retention'], priorities: ['status clarity'] },
        { id: 'support', name: 'Samuel Eze', role: 'Support Lead', department: 'Support', influence: 8, satisfaction: 42, communicationStyle: 'direct', concerns: ['ticket load', 'angry users'], priorities: ['complaint reduction'] },
        { id: 'ops', name: 'Fatima Umar', role: 'Payments Operations Lead', department: 'Operations', influence: 8, satisfaction: 60, communicationStyle: 'analytical', concerns: ['provider delays', 'refund timelines'], priorities: ['accurate state messaging'] },
        { id: 'eng', name: 'Leo Chen', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 65, communicationStyle: 'analytical', concerns: ['event reliability', 'bank provider constraints'], priorities: ['low-risk tracking UI'] },
    ],
    risks: [
        { id: 'risk-status', title: 'Incorrect transfer status could damage user trust', severity: 'critical', likelihood: 'medium' },
        { id: 'risk-provider', title: 'External provider delays may continue after UI changes', severity: 'medium', likelihood: 'high' },
        { id: 'risk-duplicate', title: 'Users may still repeat payments if warnings are unclear', severity: 'high', likelihood: 'medium' },
    ],
    kpis: [
        { id: 'satisfaction', label: 'Transfer Satisfaction', value: 61, maxValue: 100, status: 'warning', goal: 'Reach 78/100', progress: 61 },
        { id: 'success-rate', label: 'Transfer Success Rate', value: 91, maxValue: 100, status: 'good', goal: 'Maintain above 92%', progress: 91 },
        { id: 'pending', label: 'Long Pending Transfers', value: 74, maxValue: 100, status: 'warning', goal: 'Reduce uncertainty', progress: 74 },
        { id: 'tickets', label: 'Transfer Tickets', value: 82, maxValue: 100, status: 'critical', goal: 'Reduce by 30%', progress: 82 },
    ],
};

const tradePayMerchantOnboardingSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-004',
    name: 'Improve Merchant Onboarding',
    companyName: 'TradePay',
    industry: 'Fintech',
    productDescription: 'a payment collection platform for small businesses, market traders, and online sellers',
    targetUsers: 'SME merchants, Instagram sellers, POS agents, market traders, and small retail shop owners',
    businessGoal: 'Increase active merchants who complete setup and accept their first customer payment',
    mainProductProblem: 'Merchants start registration but abandon business verification, document upload, or settlement setup',
    keyMetric: 'Merchant onboarding completion rate',
    stakeholderContext: [
        'Sales says many interested merchants start registration but do not finish setup.',
        'Compliance says business verification and settlement account checks cannot be skipped.',
        'Support receives repeated questions about documents, approval status, and payment-link access.',
        'Operations wants fewer manual follow-ups from field agents.',
        'Engineering can improve flow clarity and status messaging, but cannot replace the verification provider for MVP.',
    ],
    selectedMvpFeature: 'Merchant Setup Checklist',
    selectedMvpReason: 'It shows required documents, settlement status, approval progress, and the next action needed before a merchant can accept payment.',
    finalPortfolioOutcome: 'Improving Merchant Onboarding for TradePay',
    difficulty: 'advanced',
    primaryColor: '#0ea5a3',
    budget: 180000,
    fundingStatus: 'Series A',
    employees: '78',
    headquarters: 'Lagos, Nigeria',
    technicalStack: 'React Native, React, Node.js, PostgreSQL, payment gateway APIs, KYC and KYB provider integration',
    marketContext: 'African SME payment platforms compete on fast setup, trust, settlement reliability, and low-friction merchant support.',
    existingFlow: ['Create merchant account', 'Enter business details', 'Upload documents', 'Add settlement account', 'Wait for approval', 'Accept first payment'],
    analytics: [
        'Last 30 days: 9,600 merchant signups from sales campaigns and referrals.',
        'Business details completed by 71% of merchants, but document upload completed by 39%.',
        'Settlement account added by 44% of signups.',
        'Merchant onboarding completion rate is 31%; target is 55%.',
        'Only 18% of new merchants accept a first payment within seven days.',
    ],
    userFeedback: [
        '"I sell from Instagram and do not know which business document to upload."',
        '"The app said my account is under review, but I did not know what was left."',
        '"I was not sure if my bank account had been approved for settlement."',
        '"The sales agent helped me start, but I got stuck when I was alone."',
        '"I wanted to create a payment link today, not wait without updates."',
    ],
    supportTickets: [
        'Ticket 4102: Merchant asks whether CAC is required for informal businesses.',
        'Ticket 4120: Merchant says document upload failed without a clear reason.',
        'Ticket 4155: Merchant asks why payment links are disabled after signup.',
        'Ticket 4181: Merchant wants to change settlement account after rejection.',
        'Ticket 4208: Merchant asks when account review will be completed.',
    ],
    stakeholderMemo: [
        'From: Head of Merchant Growth',
        'Sales is bringing in good merchant leads, but too many never reach first payment acceptance. Please investigate onboarding drop-off and recommend one MVP improvement that helps merchants complete setup without adding compliance risk.',
    ],
    internalNotes: [
        'Sales: Field agents spend too much time chasing merchants after signup.',
        'Compliance: Merchant category, business identity, and settlement account checks must remain mandatory.',
        'Support: Most onboarding tickets are about required documents, approval status, and rejected settlement accounts.',
        'Engineering: A checklist, clearer document guidance, and status states are feasible in three weeks.',
    ],
    featureIdeas: [
        { idea: 'Merchant setup checklist', problemSolved: 'Merchants know exactly what remains before they can accept payment.' },
        { idea: 'Document requirement guide', problemSolved: 'Merchants understand which document type fits their business.' },
        { idea: 'Settlement account status', problemSolved: 'Merchants know whether payouts are ready or blocked.' },
        { idea: 'Review timeline message', problemSolved: 'Merchants understand expected approval timing.' },
        { idea: 'Rejected document fix tips', problemSolved: 'Merchants know how to correct failed uploads.' },
    ],
    impactMapExamples: [
        { userProblem: 'Merchants do not know which documents are required', businessImpact: 'Qualified merchants abandon before approval', metricAffected: 'Merchant onboarding completion rate' },
        { userProblem: 'Approval status is unclear', businessImpact: 'Merchants contact support or stop setup', metricAffected: 'Support ticket volume' },
        { userProblem: 'Payment tools stay disabled without explanation', businessImpact: 'Merchants fail to accept a first payment', metricAffected: 'First payment acceptance rate' },
    ],
    stakeholders: [
        { id: 'growth', name: 'Kemi Adebayo', role: 'Head of Merchant Growth', department: 'Growth', influence: 10, satisfaction: 54, communicationStyle: 'direct', concerns: ['merchant activation', 'sales conversion'], priorities: ['first payment acceptance'] },
        { id: 'compliance', name: 'Musa Danladi', role: 'Compliance Manager', department: 'Compliance', influence: 9, satisfaction: 72, communicationStyle: 'formal', concerns: ['KYB requirements', 'settlement account risk'], priorities: ['regulatory adherence'] },
        { id: 'support', name: 'Chinwe Nwosu', role: 'Merchant Support Lead', department: 'Support', influence: 7, satisfaction: 49, communicationStyle: 'collaborative', concerns: ['repetitive onboarding tickets'], priorities: ['self-service setup'] },
        { id: 'ops', name: 'Kwame Mensah', role: 'Merchant Operations Lead', department: 'Operations', influence: 8, satisfaction: 58, communicationStyle: 'analytical', concerns: ['manual follow-ups', 'approval backlog'], priorities: ['faster reviews'] },
        { id: 'eng', name: 'Tariq Bello', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 66, communicationStyle: 'analytical', concerns: ['provider constraints', 'MVP scope'], priorities: ['low-risk UI changes'] },
    ],
    risks: [
        { id: 'risk-compliance', title: 'Simplified onboarding copy could imply verification is optional', severity: 'critical', likelihood: 'low' },
        { id: 'risk-documents', title: 'Document guidance may not cover every merchant category', severity: 'medium', likelihood: 'medium' },
        { id: 'risk-review-delay', title: 'Manual review delays may continue after clearer status messaging', severity: 'medium', likelihood: 'high' },
    ],
    kpis: [
        { id: 'onboarding', label: 'Merchant Onboarding Completion', value: 31, maxValue: 100, status: 'critical', goal: 'Reach 55%', progress: 31 },
        { id: 'documents', label: 'Document Upload Completion', value: 39, maxValue: 100, status: 'critical', goal: 'Reach 60%', progress: 39 },
        { id: 'first-payment', label: 'First Payment Acceptance', value: 18, maxValue: 100, status: 'critical', goal: 'Reach 35%', progress: 18 },
        { id: 'tickets', label: 'Onboarding Support Tickets', value: 76, maxValue: 100, status: 'warning', goal: 'Reduce by 25%', progress: 76 },
    ],
};

const fundlyWalletFundingDropoffSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-005',
    name: 'Reduce Wallet Funding Drop-off',
    companyName: 'Fundly',
    industry: 'Fintech',
    productDescription: 'a consumer wallet for savings, transfers, airtime, and bill payments',
    targetUsers: 'Students, young professionals, gig workers, small traders, and first-time wallet users',
    businessGoal: 'Increase successful wallet funding among new and returning users',
    mainProductProblem: 'Users start wallet funding but abandon when bank transfer instructions, fees, or confirmation timing are unclear',
    keyMetric: 'Wallet funding completion rate',
    stakeholderContext: [
        'Product wants more funded wallets because funding is the gateway to transfers, savings, and bill payments.',
        'Growth says paid acquisition is inefficient when users sign up but never add money.',
        'Support receives complaints about pending deposits, wrong transfer references, and unclear fees.',
        'Finance wants fewer failed reconciliation cases.',
        'Engineering can improve funding instructions, status tracking, and reminders using existing payment events.',
    ],
    selectedMvpFeature: 'Funding Instruction and Status Screen',
    selectedMvpReason: 'It reduces uncertainty by showing exact transfer steps, fees, reference requirements, and real-time funding status after the user starts a deposit.',
    finalPortfolioOutcome: 'Reducing Wallet Funding Drop-off for Fundly',
    difficulty: 'intro',
    primaryColor: '#16a34a',
    budget: 130000,
    fundingStatus: 'Seed stage',
    employees: '39',
    headquarters: 'Lagos, Nigeria',
    technicalStack: 'React Native, Node.js, PostgreSQL, virtual account APIs, bank transfer webhooks, payment processor integration',
    marketContext: 'Wallet users in Nigeria expect fast deposits, clear bank transfer instructions, and confidence that money will appear after debit.',
    existingFlow: ['Open wallet', 'Tap fund wallet', 'Choose funding method', 'Copy account details', 'Transfer from bank app', 'Wait for wallet credit'],
    analytics: [
        'Last 30 days: 52,000 wallet funding starts.',
        'Wallet funding completion rate is 46%; target is 65%.',
        'Bank transfer funding accounts for 72% of funding attempts.',
        '21% of bank transfer users leave the app before copying account details.',
        'Pending deposit tickets increased 28% month over month.',
    ],
    userFeedback: [
        '"I copied the account number but was not sure if I needed a reference."',
        '"My bank debited me and Fundly did not show anything for some minutes."',
        '"I did not know there was a fee until after I tried to fund."',
        '"I left to open my bank app and forgot the exact amount I wanted to send."',
        '"I was scared because the account name did not look familiar."',
    ],
    supportTickets: [
        'Ticket 5201: User asks why wallet was not credited after bank debit.',
        'Ticket 5224: User transferred without reference and requests manual tracing.',
        'Ticket 5250: User says funding fee was unclear before transfer.',
        'Ticket 5266: User asks whether virtual account name is safe.',
        'Ticket 5293: User started funding but could not find pending deposit status.',
    ],
    stakeholderMemo: [
        'From: Product Lead',
        'Wallet funding is our biggest activation bottleneck. Please review where users drop off and propose one MVP improvement that helps users complete funding with more confidence and fewer support escalations.',
    ],
    internalNotes: [
        'Growth: Acquisition campaigns drive installs, but unfunded wallets rarely retain.',
        'Support: Pending deposits and missing references create avoidable tickets.',
        'Finance: Manual reconciliation is costly when users send incomplete transfer details.',
        'Engineering: Webhook events already exist, but user-facing status is limited.',
    ],
    featureIdeas: [
        { idea: 'Funding instruction screen', problemSolved: 'Users understand exact bank transfer steps before leaving the app.' },
        { idea: 'Funding status tracker', problemSolved: 'Users know whether a deposit is pending, credited, or needs review.' },
        { idea: 'Fee preview', problemSolved: 'Users see charges before starting funding.' },
        { idea: 'Reference reminder', problemSolved: 'Users avoid transfers that require manual reconciliation.' },
        { idea: 'Return-to-funding reminder', problemSolved: 'Users who leave for their bank app can continue the funding flow.' },
    ],
    impactMapExamples: [
        { userProblem: 'Bank transfer instructions are unclear', businessImpact: 'Users abandon before funding wallet', metricAffected: 'Wallet funding completion rate' },
        { userProblem: 'Pending deposit status is not visible', businessImpact: 'Users lose trust and contact support', metricAffected: 'Funding support ticket volume' },
        { userProblem: 'Funding fees appear late', businessImpact: 'Users feel surprised and quit the flow', metricAffected: 'Funding conversion rate' },
    ],
    stakeholders: [
        { id: 'product', name: 'Efe Johnson', role: 'Product Lead', department: 'Product', influence: 10, satisfaction: 56, communicationStyle: 'direct', concerns: ['funding conversion', 'activation'], priorities: ['wallet funding completion'] },
        { id: 'growth', name: 'Ayo Balogun', role: 'Growth Manager', department: 'Growth', influence: 8, satisfaction: 52, communicationStyle: 'analytical', concerns: ['CAC payback', 'unfunded signups'], priorities: ['activated users'] },
        { id: 'support', name: 'Ngozi Eze', role: 'Support Lead', department: 'Support', influence: 7, satisfaction: 48, communicationStyle: 'collaborative', concerns: ['pending deposit complaints'], priorities: ['ticket reduction'] },
        { id: 'finance', name: 'Sola Yusuf', role: 'Finance Operations Lead', department: 'Finance', influence: 8, satisfaction: 61, communicationStyle: 'formal', concerns: ['manual reconciliation', 'missing references'], priorities: ['accurate settlement records'] },
        { id: 'eng', name: 'Daniel Boateng', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 67, communicationStyle: 'analytical', concerns: ['webhook reliability', 'payment provider limits'], priorities: ['clear event states'] },
    ],
    risks: [
        { id: 'risk-webhook-delay', title: 'Provider webhook delays may still make deposits appear pending', severity: 'high', likelihood: 'medium' },
        { id: 'risk-reference', title: 'Users may ignore reference instructions when switching to bank apps', severity: 'medium', likelihood: 'high' },
        { id: 'risk-fee-trust', title: 'Fee messaging could reduce completion if framed poorly', severity: 'medium', likelihood: 'medium' },
    ],
    kpis: [
        { id: 'funding-completion', label: 'Wallet Funding Completion', value: 46, maxValue: 100, status: 'warning', goal: 'Reach 65%', progress: 46 },
        { id: 'copy-details', label: 'Account Details Copied', value: 79, maxValue: 100, status: 'good', goal: 'Reach 85%', progress: 79 },
        { id: 'pending-tickets', label: 'Pending Deposit Tickets', value: 72, maxValue: 100, status: 'critical', goal: 'Reduce by 30%', progress: 72 },
        { id: 'first-funded-wallet', label: 'New User Funded Wallets', value: 33, maxValue: 100, status: 'critical', goal: 'Reach 50%', progress: 33 },
    ],
};

const billMateBillPaymentSuccessSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-006',
    name: 'Improve Bill Payment Success',
    companyName: 'BillMate',
    industry: 'Fintech',
    productDescription: 'a bill payment app for airtime, data, electricity, cable TV, education, and internet payments',
    targetUsers: 'Urban families, students, salary earners, small merchants, and agents who pay recurring bills',
    businessGoal: 'Increase successful bill payments and reduce failed payment complaints',
    mainProductProblem: 'Users attempt bill payments but failures, unclear biller validation, and weak retry guidance reduce trust and repeat usage',
    keyMetric: 'Bill payment success rate',
    stakeholderContext: [
        'Product wants more repeat bill payments because recurring usage drives retention.',
        'Operations says many failures come from biller downtime, invalid meter numbers, and delayed provider confirmation.',
        'Support receives urgent complaints when electricity tokens, data bundles, or cable renewals are delayed.',
        'Marketing wants to promote reliability, but current failures create trust risk.',
        'Engineering can improve validation, status messaging, and retry flows using existing provider responses.',
    ],
    selectedMvpFeature: 'Bill Payment Validation and Status Tracker',
    selectedMvpReason: 'It checks biller details before payment, shows processing status after debit, and gives users clear next steps for success, retry, or reversal.',
    finalPortfolioOutcome: 'Improving Bill Payment Success for BillMate',
    difficulty: 'intermediate',
    primaryColor: '#f97316',
    budget: 160000,
    fundingStatus: 'Pre-Series A',
    employees: '58',
    headquarters: 'Lagos, Nigeria',
    technicalStack: 'React Native, Node.js, PostgreSQL, biller aggregator APIs, payment gateway APIs, notification service',
    marketContext: 'Bill payment apps in Africa compete on successful delivery, transparent provider status, and fast resolution when billers are unavailable.',
    existingFlow: ['Choose bill category', 'Enter customer details', 'Validate biller account', 'Confirm amount', 'Pay', 'Receive token or receipt'],
    analytics: [
        'Last 30 days: 310,000 bill payment attempts.',
        'Overall bill payment success rate is 87.5%; target is 94%.',
        'Electricity payments have the highest complaint rate at 12% of attempts.',
        'Cable TV validation failures account for 18% of failed bill sessions.',
        'Support receives 4,900 bill payment tickets per month, mostly about tokens, reversals, and delayed value delivery.',
    ],
    userFeedback: [
        '"I paid for electricity but did not get my token immediately."',
        '"The app accepted the meter number, then failed after debit."',
        '"I did not know if I should retry or wait."',
        '"My cable subscription did not renew and I had no clear update."',
        '"I need to know when failed bill payments reverse."',
    ],
    supportTickets: [
        'Ticket 6105: User paid electricity bill but token was delayed.',
        'Ticket 6122: User entered wrong smart card number and payment failed.',
        'Ticket 6150: User asks whether to retry after provider timeout.',
        'Ticket 6187: User requests reversal timeline for failed data purchase.',
        'Ticket 6203: User says receipt does not prove biller received payment.',
    ],
    stakeholderMemo: [
        'From: VP Product',
        'Bill payments should feel dependable because they are urgent and recurring. Please investigate the success-rate gap and recommend one MVP improvement that reduces failed payment confusion and increases repeat usage.',
    ],
    internalNotes: [
        'Operations: Biller downtime and delayed confirmation are common during peak evening periods.',
        'Support: Users need clearer token delivery, retry, and reversal guidance.',
        'Engineering: Provider validation responses are available for major billers, but not all aggregators return the same fields.',
        'Marketing: Reliability claims must match the user experience.',
    ],
    featureIdeas: [
        { idea: 'Biller validation preview', problemSolved: 'Users confirm customer details before paying.' },
        { idea: 'Bill payment status tracker', problemSolved: 'Users know whether value delivery is processing, successful, failed, or reversing.' },
        { idea: 'Provider downtime message', problemSolved: 'Users avoid paying when a biller is temporarily unavailable.' },
        { idea: 'Smart retry guidance', problemSolved: 'Users know when to retry and when to wait.' },
        { idea: 'Token and receipt center', problemSolved: 'Users can find electricity tokens and bill receipts after payment.' },
    ],
    impactMapExamples: [
        { userProblem: 'Invalid biller details are caught too late', businessImpact: 'Users experience failed payments after debit', metricAffected: 'Bill payment success rate' },
        { userProblem: 'Token delivery status is unclear', businessImpact: 'Users contact support and lose trust', metricAffected: 'Bill payment satisfaction' },
        { userProblem: 'Retry guidance is missing after provider timeout', businessImpact: 'Users may duplicate payments or abandon BillMate', metricAffected: 'Repeat bill payment rate' },
    ],
    stakeholders: [
        { id: 'product', name: 'Amaka Obi', role: 'VP Product', department: 'Product', influence: 10, satisfaction: 58, communicationStyle: 'direct', concerns: ['payment reliability', 'repeat usage'], priorities: ['bill payment success'] },
        { id: 'ops', name: 'Ibrahim Sule', role: 'Biller Operations Lead', department: 'Operations', influence: 8, satisfaction: 57, communicationStyle: 'analytical', concerns: ['provider downtime', 'token delays'], priorities: ['accurate provider status'] },
        { id: 'support', name: 'Linda Achieng', role: 'Customer Support Lead', department: 'Support', influence: 8, satisfaction: 45, communicationStyle: 'collaborative', concerns: ['urgent bill complaints', 'reversal questions'], priorities: ['fewer escalations'] },
        { id: 'marketing', name: 'Femi Cole', role: 'Marketing Lead', department: 'Marketing', influence: 7, satisfaction: 60, communicationStyle: 'direct', concerns: ['trust claims', 'negative reviews'], priorities: ['reliable brand promise'] },
        { id: 'eng', name: 'Ada Mensah', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 64, communicationStyle: 'analytical', concerns: ['aggregator inconsistencies', 'status mapping'], priorities: ['stable provider integration'] },
    ],
    risks: [
        { id: 'risk-provider-data', title: 'Aggregator responses may be inconsistent across bill categories', severity: 'high', likelihood: 'medium' },
        { id: 'risk-token-delay', title: 'Provider token delays may continue even with better status messaging', severity: 'medium', likelihood: 'high' },
        { id: 'risk-duplicate-payment', title: 'Poor retry guidance could cause duplicate bill payments', severity: 'critical', likelihood: 'medium' },
    ],
    kpis: [
        { id: 'success-rate', label: 'Bill Payment Success Rate', value: 88, maxValue: 100, status: 'warning', goal: 'Reach 94%', progress: 88 },
        { id: 'validation', label: 'Successful Biller Validation', value: 76, maxValue: 100, status: 'warning', goal: 'Reach 88%', progress: 76 },
        { id: 'repeat-usage', label: 'Repeat Bill Payment Usage', value: 41, maxValue: 100, status: 'warning', goal: 'Reach 55%', progress: 41 },
        { id: 'tickets', label: 'Bill Payment Tickets', value: 69, maxValue: 100, status: 'critical', goal: 'Reduce by 25%', progress: 69 },
    ],
};

const creditEaseLoanCompletionSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-007',
    name: 'Improve Loan Application Completion',
    companyName: 'CreditEase',
    industry: 'Fintech',
    productDescription: 'a mobile lending app offering small personal and salary-backed loans',
    targetUsers: 'Salary earners, gig workers, small traders, and repeat mobile money users in Nigeria',
    businessGoal: 'Increase completed loan applications without weakening credit risk checks',
    mainProductProblem: 'Users start loan applications but abandon when asked for employment, bank statement, or repayment details',
    keyMetric: 'Loan application completion rate',
    stakeholderContext: [
        'Product wants more qualified applications reaching decisioning.',
        'Risk says affordability and identity checks cannot be skipped.',
        'Support receives questions about required documents and repayment terms.',
        'Growth says paid acquisition is bringing applicants who do not finish.',
        'Engineering can improve the form flow, save progress, and add clearer guidance.',
    ],
    selectedMvpFeature: 'Loan Application Progress Guide',
    selectedMvpReason: 'It breaks the application into clear steps, explains why each item is needed, and lets users return to incomplete applications.',
    finalPortfolioOutcome: 'Improving Loan Application Completion for CreditEase',
    difficulty: 'advanced',
    primaryColor: '#0f766e',
    budget: 140000,
    fundingStatus: 'Series A',
    employees: '58',
    headquarters: 'Lagos, Nigeria',
    technicalStack: 'React Native, Node.js, PostgreSQL, credit scoring engine, bank statement API, KYC provider',
    marketContext: 'Digital lenders in Nigeria compete on speed, transparency, fair terms, and responsible credit decisions.',
    existingFlow: ['Choose loan amount', 'Enter personal details', 'Verify identity', 'Connect bank statement', 'Review offer', 'Submit application'],
    analytics: [
        'Last 30 days: 31,500 loan applications started.',
        'Application completion rate is 41%; target is 60%.',
        'Drop-off is highest on bank statement connection and employment details.',
        '23% of users who abandon return within seven days but restart from the beginning.',
        'Approved completed applications convert to disbursement at 72%.',
    ],
    userFeedback: [
        '"I did not know why you needed my bank statement."',
        '"The form was too long and I could not finish during work break."',
        '"I wanted to check the repayment amount before giving more details."',
        '"I left the app and had to start again."',
        '"I was not sure if connecting my bank account was safe."',
    ],
    supportTickets: [
        'Ticket 7102: User asks why bank statement access is required for a small loan.',
        'Ticket 7145: User lost progress after leaving the employment details screen.',
        'Ticket 7180: User asks whether repayment amount can change after approval.',
        'Ticket 7211: User says bank connection failed twice with no next step.',
        'Ticket 7244: User asks if salary account is mandatory.',
    ],
    stakeholderMemo: [
        'From: Head of Lending Product',
        'We have strong demand but too many incomplete applications. Please identify the main blockers and recommend one MVP improvement that helps eligible users submit applications while keeping risk controls intact.',
    ],
    internalNotes: [
        'Risk: Income, identity, and affordability checks are mandatory.',
        'Support: Users need clearer explanations for bank statement access and repayment terms.',
        'Growth: Acquisition cost is rising, so incomplete applications are expensive.',
        'Engineering: Save progress and step-level guidance are feasible within three weeks.',
    ],
    featureIdeas: [
        { idea: 'Application progress guide', problemSolved: 'Users understand remaining steps and why each step matters.' },
        { idea: 'Save and resume application', problemSolved: 'Users can return without restarting.' },
        { idea: 'Bank statement trust explainer', problemSolved: 'Users feel safer connecting financial data.' },
        { idea: 'Repayment preview', problemSolved: 'Users understand estimated repayment before submission.' },
        { idea: 'Bank connection fallback', problemSolved: 'Users know what to do when account linking fails.' },
    ],
    impactMapExamples: [
        { userProblem: 'Users do not trust bank statement connection', businessImpact: 'Qualified borrowers abandon before underwriting', metricAffected: 'Application completion rate' },
        { userProblem: 'Application feels too long', businessImpact: 'Users leave before submitting required information', metricAffected: 'Loan funnel completion' },
        { userProblem: 'Repayment terms are unclear', businessImpact: 'Users hesitate to continue or contact support', metricAffected: 'Support ticket volume' },
    ],
    stakeholders: [
        { id: 'product', name: 'Kemi Balogun', role: 'Head of Lending Product', department: 'Product', influence: 10, satisfaction: 58, communicationStyle: 'direct', concerns: ['application drop-off', 'loan funnel quality'], priorities: ['completed qualified applications'] },
        { id: 'risk', name: 'Musa Danjuma', role: 'Credit Risk Lead', department: 'Risk', influence: 10, satisfaction: 70, communicationStyle: 'analytical', concerns: ['affordability checks', 'fraud risk'], priorities: ['responsible lending'] },
        { id: 'growth', name: 'Ada Nwosu', role: 'Growth Lead', department: 'Growth', influence: 8, satisfaction: 54, communicationStyle: 'analytical', concerns: ['wasted acquisition spend'], priorities: ['conversion efficiency'] },
        { id: 'support', name: 'Chinedu Obi', role: 'Support Manager', department: 'Support', influence: 7, satisfaction: 49, communicationStyle: 'collaborative', concerns: ['document questions', 'repayment confusion'], priorities: ['ticket reduction'] },
        { id: 'eng', name: 'Tariq Hassan', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 66, communicationStyle: 'analytical', concerns: ['bank API reliability', 'scope control'], priorities: ['simple resumable flow'] },
    ],
    risks: [
        { id: 'risk-credit-controls', title: 'MVP could be perceived as reducing required credit checks', severity: 'critical', likelihood: 'low' },
        { id: 'risk-bank-link', title: 'External bank statement connection failures may continue', severity: 'high', likelihood: 'medium' },
        { id: 'risk-overpromising', title: 'Repayment preview may be mistaken for guaranteed approval', severity: 'high', likelihood: 'medium' },
    ],
    kpis: [
        { id: 'completion', label: 'Application Completion', value: 41, maxValue: 100, status: 'critical', goal: 'Reach 60%', progress: 41 },
        { id: 'bank-connect', label: 'Bank Statement Connection', value: 46, maxValue: 100, status: 'warning', goal: 'Reach 62%', progress: 46 },
        { id: 'qualified-submit', label: 'Qualified Submissions', value: 52, maxValue: 100, status: 'warning', goal: 'Reach 68%', progress: 52 },
        { id: 'loan-support', label: 'Loan Application Tickets', value: 71, maxValue: 100, status: 'critical', goal: 'Reduce by 25%', progress: 71 },
    ],
};

const safePayFraudAlertSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-008',
    name: 'Improve Fraud Alert Experience',
    companyName: 'SafePay',
    industry: 'Fintech',
    productDescription: 'a secure mobile wallet with card, transfer, and suspicious-activity monitoring',
    targetUsers: 'Urban wallet users, online shoppers, small business owners, and frequent transfer users',
    businessGoal: 'Help users act quickly on suspicious activity while preserving trust in legitimate transactions',
    mainProductProblem: 'Users receive suspicious transaction alerts but do not understand what happened or what action to take',
    keyMetric: 'Fraud alert response rate',
    stakeholderContext: [
        'Risk wants faster user confirmation on suspicious activity.',
        'Support says users panic after vague fraud notifications.',
        'Product wants a clear in-app path for reviewing and responding to alerts.',
        'Compliance needs audit-friendly user decisions and escalation records.',
        'Engineering can add alert detail screens and basic transaction controls for MVP.',
    ],
    selectedMvpFeature: 'Fraud Alert Action Screen',
    selectedMvpReason: 'It gives users one clear place to review suspicious activity, confirm or block it, freeze risky actions, and contact support if needed.',
    finalPortfolioOutcome: 'Improving Fraud Alert Experience for SafePay',
    difficulty: 'advanced',
    primaryColor: '#dc2626',
    budget: 180000,
    fundingStatus: 'Series B',
    employees: '120',
    headquarters: 'Lagos, Nigeria',
    technicalStack: 'React Native, Node.js, PostgreSQL, fraud rules engine, card processor APIs, notification service',
    marketContext: 'Payments users expect instant fraud protection, but false alarms can damage trust and block legitimate transactions.',
    existingFlow: ['Alert sent', 'User opens alert', 'Generic warning shown', 'User decides action', 'Support escalation if unresolved'],
    analytics: [
        'Last 30 days: 19,800 fraud alerts triggered.',
        'Only 37% of alerts receive a user response within one hour.',
        '18% of users who receive an alert contact support before taking any action.',
        'False positive rate is estimated at 21% for travel and online shopping transactions.',
        'Confirmed fraud losses are up 14% quarter over quarter.',
    ],
    userFeedback: [
        '"The alert said suspicious activity but did not show what happened."',
        '"I wanted to freeze my account but could not find the button."',
        '"My card was blocked and I did not know how to confirm it was me."',
        '"I was scared my money had already gone."',
        '"Support asked questions I thought the app should already know."',
    ],
    supportTickets: [
        'Ticket 8208: User asks whether a flagged card charge has already debited their wallet.',
        'Ticket 8240: User wants to unblock a legitimate online purchase.',
        'Ticket 8277: User cannot find where to report an unknown transfer attempt.',
        'Ticket 8312: User asks if they should change PIN after fraud alert.',
        'Ticket 8351: User complains that account was restricted without clear next steps.',
    ],
    stakeholderMemo: [
        'From: Risk Operations Lead',
        'Fraud alerts are increasing, but users are not responding quickly enough. Please recommend an MVP that helps users understand alerts, take the right action, and reduce unnecessary support escalation.',
    ],
    internalNotes: [
        'Risk: Alerts must make suspicious amount, merchant, channel, and time clear.',
        'Compliance: User confirmation or rejection should be logged for investigations.',
        'Support: Users need plain-language next steps before opening a ticket.',
        'Engineering: Temporary card freeze and alert detail screens are feasible; full fraud model changes are out of scope.',
    ],
    featureIdeas: [
        { idea: 'Fraud alert action screen', problemSolved: 'Users can review and resolve alerts in one place.' },
        { idea: 'Transaction detail card', problemSolved: 'Users understand suspicious activity before acting.' },
        { idea: 'Freeze card or wallet action', problemSolved: 'Users can protect themselves immediately.' },
        { idea: 'Confirm transaction button', problemSolved: 'Legitimate transactions can be unblocked faster.' },
        { idea: 'Security checklist', problemSolved: 'Users know whether to change PIN, password, or contact support.' },
    ],
    impactMapExamples: [
        { userProblem: 'Fraud alert is vague', businessImpact: 'Users delay response and fraud exposure increases', metricAffected: 'Fraud alert response rate' },
        { userProblem: 'No immediate safety action', businessImpact: 'Users panic and overload support', metricAffected: 'Fraud support tickets' },
        { userProblem: 'False positives block good users', businessImpact: 'Legitimate payments fail and trust declines', metricAffected: 'Legitimate transaction completion' },
    ],
    stakeholders: [
        { id: 'risk', name: 'Ibrahim Yusuf', role: 'Risk Operations Lead', department: 'Risk', influence: 10, satisfaction: 55, communicationStyle: 'analytical', concerns: ['fraud losses', 'slow response'], priorities: ['fast alert resolution'] },
        { id: 'product', name: 'Ezinne Okoro', role: 'Product Manager', department: 'Product', influence: 9, satisfaction: 60, communicationStyle: 'collaborative', concerns: ['trust', 'blocked payments'], priorities: ['clear user action'] },
        { id: 'support', name: 'Ronke Adebayo', role: 'Customer Support Lead', department: 'Support', influence: 7, satisfaction: 46, communicationStyle: 'direct', concerns: ['panic tickets', 'manual investigations'], priorities: ['self-service resolution'] },
        { id: 'compliance', name: 'Nadia Sule', role: 'Compliance Officer', department: 'Compliance', influence: 9, satisfaction: 68, communicationStyle: 'formal', concerns: ['audit trails', 'customer protection'], priorities: ['logged decisions'] },
        { id: 'eng', name: 'Michael Essien', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 63, communicationStyle: 'analytical', concerns: ['real-time state accuracy', 'processor limits'], priorities: ['reliable alert UI'] },
    ],
    risks: [
        { id: 'risk-false-positive', title: 'Too much friction could block legitimate payments', severity: 'high', likelihood: 'medium' },
        { id: 'risk-wrong-state', title: 'Incorrect alert status could mislead users during fraud events', severity: 'critical', likelihood: 'medium' },
        { id: 'risk-security-copy', title: 'Unclear guidance could cause users to ignore real fraud', severity: 'critical', likelihood: 'low' },
    ],
    kpis: [
        { id: 'resolution', label: 'Fraud Alert Response', value: 37, maxValue: 100, status: 'critical', goal: 'Reach 65%', progress: 37 },
        { id: 'response-time', label: 'One Hour Response', value: 37, maxValue: 100, status: 'critical', goal: 'Reach 60%', progress: 37 },
        { id: 'fraud-loss', label: 'Fraud Loss Pressure', value: 78, maxValue: 100, status: 'critical', goal: 'Reduce by 20%', progress: 78 },
        { id: 'support-load', label: 'Fraud Support Tickets', value: 69, maxValue: 100, status: 'warning', goal: 'Reduce by 30%', progress: 69 },
    ],
};

const savewiseSavingsActivationSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-009',
    name: 'Improve Savings Plan Activation',
    companyName: 'Savewise',
    industry: 'Fintech',
    productDescription: 'a savings app that helps users create automated plans for rent, school fees, emergencies, and personal goals',
    targetUsers: 'Young professionals, students, parents, freelancers, and informal workers building savings habits',
    businessGoal: 'Increase users who activate their first funded savings plan',
    mainProductProblem: 'Users view the savings feature or create goals but do not fund or automate a plan',
    keyMetric: 'Savings plan activation rate',
    stakeholderContext: [
        'Product wants users to reach the first moment of value by funding a plan.',
        'Growth says campaign signups are interested in saving but delay funding.',
        'Finance wants predictable wallet inflows from automated plans.',
        'Support receives questions about locked savings, withdrawals, and missed deposits.',
        'Engineering can improve plan setup, reminders, and payment prompts for MVP.',
    ],
    selectedMvpFeature: 'Guided Savings Goal Setup',
    selectedMvpReason: 'It helps users choose a realistic amount, understand rules, and fund or schedule the first deposit before leaving setup.',
    finalPortfolioOutcome: 'Improving Savings Plan Activation for Savewise',
    difficulty: 'intermediate',
    primaryColor: '#15803d',
    budget: 95000,
    fundingStatus: 'Seed stage',
    employees: '31',
    headquarters: 'Accra, Ghana',
    technicalStack: 'React Native, Node.js, PostgreSQL, payment gateway, bank transfer APIs, notification service',
    marketContext: 'Savings products in African fintech must build trust, explain withdrawal rules, and make first deposits easy for variable-income users.',
    existingFlow: ['Open savings', 'Choose plan type', 'Enter target amount', 'Set frequency', 'Fund plan', 'Track progress'],
    analytics: [
        'Last 30 days: 22,700 savings goals created.',
        'Only 28% of created goals receive a first deposit within 24 hours.',
        'Plan activation rate is 32%; target is 55%.',
        'Users who activate auto-save retain 2.4x better after 60 days.',
        'Drop-off is highest after users select deposit frequency.',
    ],
    userFeedback: [
        '"I made a rent goal but did not know how much to start with."',
        '"I was worried I would not be able to withdraw in an emergency."',
        '"Auto-save sounds good, but my income is not fixed."',
        '"I forgot to fund the plan after creating it."',
        '"I wanted to see what happens if I miss a weekly deposit."',
    ],
    supportTickets: [
        'Ticket 9103: User asks if locked savings can be withdrawn early.',
        'Ticket 9144: User created a school fees goal but cannot find how to fund it.',
        'Ticket 9182: User asks whether auto-save can be paused.',
        'Ticket 9219: User wants to change savings frequency before first deposit.',
        'Ticket 9241: User asks if bank transfer funding reflects instantly.',
    ],
    stakeholderMemo: [
        'From: Product Lead',
        'Goal creation is healthy, but too many users stop before funding. Please investigate the activation gap and recommend a focused MVP that helps users start saving with confidence.',
    ],
    internalNotes: [
        'Finance: Activated auto-save plans create more predictable inflows.',
        'Support: Withdrawal rules and missed-deposit concerns create hesitation.',
        'Growth: Users respond well to rent, school fees, and emergency goal campaigns.',
        'Engineering: Setup guidance, reminders, and first-deposit prompts are in scope.',
    ],
    featureIdeas: [
        { idea: 'Guided savings goal setup', problemSolved: 'Users choose realistic plan terms and fund before leaving.' },
        { idea: 'Flexible auto-save option', problemSolved: 'Users with variable income can start without fear.' },
        { idea: 'Withdrawal rules summary', problemSolved: 'Users understand access and penalty rules upfront.' },
        { idea: 'First deposit reminder', problemSolved: 'Users who create goals are nudged to activate them.' },
        { idea: 'Suggested starter amount', problemSolved: 'Users avoid paralysis when choosing deposit size.' },
    ],
    impactMapExamples: [
        { userProblem: 'Users do not know how much to start with', businessImpact: 'Goals are created but not funded', metricAffected: 'Savings plan activation rate' },
        { userProblem: 'Withdrawal rules feel unclear', businessImpact: 'Users hesitate to commit money', metricAffected: 'First deposit completion' },
        { userProblem: 'Auto-save feels risky for variable income', businessImpact: 'Users avoid automation and churn early', metricAffected: 'Auto-save activation' },
    ],
    stakeholders: [
        { id: 'product', name: 'Ama Boateng', role: 'Product Lead', department: 'Product', influence: 10, satisfaction: 59, communicationStyle: 'collaborative', concerns: ['activation gap', 'first deposit'], priorities: ['funded plans'] },
        { id: 'growth', name: 'Seyi Martins', role: 'Growth Manager', department: 'Growth', influence: 8, satisfaction: 56, communicationStyle: 'analytical', concerns: ['campaign conversion', 'inactive goals'], priorities: ['signup to activation'] },
        { id: 'finance', name: 'Kwame Mensah', role: 'Finance Lead', department: 'Finance', influence: 8, satisfaction: 64, communicationStyle: 'formal', concerns: ['wallet inflows', 'plan funding'], priorities: ['auto-save adoption'] },
        { id: 'support', name: 'Yaa Donkor', role: 'Support Lead', department: 'Support', influence: 7, satisfaction: 53, communicationStyle: 'collaborative', concerns: ['withdrawal confusion', 'missed deposits'], priorities: ['clear rules'] },
        { id: 'eng', name: 'Fola Ajayi', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 67, communicationStyle: 'analytical', concerns: ['payment reliability', 'notification scope'], priorities: ['low-risk activation prompts'] },
    ],
    risks: [
        { id: 'risk-rules', title: 'Savings rules may be misunderstood if summarized too simply', severity: 'high', likelihood: 'medium' },
        { id: 'risk-overcommit', title: 'Users may choose unrealistic deposits and fail early', severity: 'medium', likelihood: 'medium' },
        { id: 'risk-payment', title: 'Funding delays could reduce confidence after setup', severity: 'medium', likelihood: 'medium' },
    ],
    kpis: [
        { id: 'activation', label: 'Plan Activation', value: 32, maxValue: 100, status: 'critical', goal: 'Reach 55%', progress: 32 },
        { id: 'first-deposit', label: 'First Deposit in 24h', value: 28, maxValue: 100, status: 'critical', goal: 'Reach 45%', progress: 28 },
        { id: 'autosave', label: 'Auto-save Adoption', value: 24, maxValue: 100, status: 'warning', goal: 'Reach 40%', progress: 24 },
        { id: 'retention', label: '60 Day Saver Retention', value: 48, maxValue: 100, status: 'warning', goal: 'Reach 62%', progress: 48 },
    ],
};

const helpPaySelfServiceSpec: ProductManagementSimulationSpec = {
    id: 'sim-pm-fintech-010',
    name: 'Improve Customer Support Self-Service',
    companyName: 'HelpPay',
    industry: 'Fintech',
    productDescription: 'a digital wallet with in-app support for transfers, funding, KYC, and bill payments',
    targetUsers: 'Everyday wallet users, bill payers, small merchants, students, and families managing recurring payments',
    businessGoal: 'Reduce repetitive support tickets while helping users resolve common issues faster',
    mainProductProblem: 'Users contact support for common issues because status, refund, KYC, and transaction help is hard to find',
    keyMetric: 'Support ticket deflection rate',
    stakeholderContext: [
        'Support is overloaded with repeat questions about pending bills, reversals, wallet funding, and receipts.',
        'Product wants users to resolve common issues inside the app.',
        'Operations says many issues have known statuses and timelines.',
        'Engineering can expose help articles, transaction status, and guided issue flows for MVP.',
        'Compliance wants support responses to avoid unsupported refund promises.',
    ],
    selectedMvpFeature: 'Searchable Transaction Help Center',
    selectedMvpReason: 'It connects common support issues to relevant articles, transaction status, refund timelines, receipts, and guided reporting before users open a support chat.',
    finalPortfolioOutcome: 'Improving Customer Support Self-Service for HelpPay',
    difficulty: 'intermediate',
    primaryColor: '#2563eb',
    budget: 125000,
    fundingStatus: 'Pre-Series A',
    employees: '47',
    headquarters: 'Lagos, Nigeria',
    technicalStack: 'React Native, Node.js, PostgreSQL, biller APIs, payment processor APIs, helpdesk integration',
    marketContext: 'Fintech support teams need self-service experiences that preserve trust when transactions are delayed or confusing.',
    existingFlow: ['User has issue', 'Opens support', 'Sends message', 'Waits for agent', 'Agent asks for transaction details', 'Resolution'],
    analytics: [
        'Last 30 days: 310,000 bill and transfer transactions.',
        'Support receives 12,400 tickets per month; 54% are repeat issue types.',
        'Self-service resolution rate is 18%; target is 45%.',
        'Electricity token delays account for 26% of support tickets.',
        'Average first response time is seven hours during evening peak periods.',
    ],
    userFeedback: [
        '"I paid for electricity but did not get my token."',
        '"I just need to know if my failed bill payment will reverse."',
        '"The receipt did not help me explain the issue."',
        '"I waited hours for support to say the payment was still processing."',
        '"I do not know which transaction to select when reporting a problem."',
    ],
    supportTickets: [
        'Ticket 10102: User asks when pending electricity token will arrive.',
        'Ticket 10140: User requests reversal for failed TV subscription payment.',
        'Ticket 10195: User asks for a receipt with meter number and payment reference.',
        'Ticket 10233: User reports duplicate airtime purchase after retrying.',
        'Ticket 10288: User wants to know why internet subscription has not activated.',
    ],
    stakeholderMemo: [
        'From: Customer Experience Director',
        'Our support team is spending too much time answering the same payment questions. Please recommend an MVP that helps users resolve common issues themselves while escalating only cases that need an agent.',
    ],
    internalNotes: [
        'Support: Most repeat tickets need status, receipt, refund timeline, or biller reference.',
        'Operations: Many biller delays resolve within 30 minutes, but users are not told this clearly.',
        'Engineering: Transaction metadata and status codes are available for most biller APIs.',
        'Compliance: Refund language must describe expected timelines, not guarantees.',
    ],
    featureIdeas: [
        { idea: 'Searchable help center', problemSolved: 'Users find answers faster without waiting for an agent.' },
        { idea: 'Transaction-specific help', problemSolved: 'Users get help based on the exact transaction they are worried about.' },
        { idea: 'Guided issue reporting', problemSolved: 'Users provide the right details before escalation.' },
        { idea: 'Refund timeline explainer', problemSolved: 'Users know when failed payments usually reverse.' },
        { idea: 'Top issue shortcuts', problemSolved: 'Users can quickly access common topics like KYC, funding, bill receipts, and failed transfers.' },
    ],
    impactMapExamples: [
        { userProblem: 'Users cannot find transaction-specific help', businessImpact: 'Repeat tickets increase and support response slows', metricAffected: 'Support ticket deflection rate' },
        { userProblem: 'Refund timelines are unclear', businessImpact: 'Users open multiple tickets for the same issue', metricAffected: 'Duplicate ticket rate' },
        { userProblem: 'Biller delays are not explained', businessImpact: 'Users lose trust in successful but delayed payments', metricAffected: 'Payment satisfaction score' },
    ],
    stakeholders: [
        { id: 'cx', name: 'Blessing Udo', role: 'Customer Experience Director', department: 'Support', influence: 10, satisfaction: 44, communicationStyle: 'direct', concerns: ['ticket volume', 'slow responses'], priorities: ['self-service resolution'] },
        { id: 'product', name: 'Ope Akinola', role: 'Product Manager', department: 'Product', influence: 9, satisfaction: 58, communicationStyle: 'collaborative', concerns: ['issue discovery', 'user trust'], priorities: ['transaction-based help'] },
        { id: 'ops', name: 'Nana Kofi', role: 'Biller Operations Lead', department: 'Operations', influence: 8, satisfaction: 61, communicationStyle: 'analytical', concerns: ['biller delays', 'status accuracy'], priorities: ['clear timelines'] },
        { id: 'eng', name: 'Peter Nnamdi', role: 'Engineering Lead', department: 'Engineering', influence: 8, satisfaction: 65, communicationStyle: 'analytical', concerns: ['API status coverage', 'helpdesk integration'], priorities: ['metadata reuse'] },
        { id: 'compliance', name: 'Zainab Bello', role: 'Compliance Lead', department: 'Compliance', influence: 8, satisfaction: 69, communicationStyle: 'formal', concerns: ['refund claims', 'complaint records'], priorities: ['accurate language'] },
    ],
    risks: [
        { id: 'risk-status-accuracy', title: 'Incorrect transaction status could increase complaints', severity: 'high', likelihood: 'medium' },
        { id: 'risk-refund-promises', title: 'Refund timeline copy may sound like a guarantee', severity: 'high', likelihood: 'medium' },
        { id: 'risk-low-adoption', title: 'Users may still open chat first if help entry points are hidden', severity: 'medium', likelihood: 'high' },
    ],
    kpis: [
        { id: 'self-service', label: 'Ticket Deflection', value: 18, maxValue: 100, status: 'critical', goal: 'Reach 45%', progress: 18 },
        { id: 'repeat-tickets', label: 'Repeat Ticket Share', value: 54, maxValue: 100, status: 'critical', goal: 'Reduce to 35%', progress: 54 },
        { id: 'response-time', label: 'First Response Pressure', value: 70, maxValue: 100, status: 'warning', goal: 'Reduce peak delays', progress: 70 },
        { id: 'payment-satisfaction', label: 'Payment Help Satisfaction', value: 56, maxValue: 100, status: 'warning', goal: 'Reach 75/100', progress: 56 },
    ],
};

export const PAYLOOP_FIRST_TRANSACTION_CONFIG = buildProductManagementSimulation(payLoopSpec);
export const VERICASH_KYC_CONFIG = buildProductManagementSimulation(veriCashSpec);
export const SWIFTPAY_FAILED_TRANSFER_CONFIG = buildProductManagementSimulation(swiftPaySpec);
export const TRADEPAY_MERCHANT_ONBOARDING_CONFIG = buildProductManagementSimulation(tradePayMerchantOnboardingSpec);
export const FUNDLY_WALLET_FUNDING_CONFIG = buildProductManagementSimulation(fundlyWalletFundingDropoffSpec);
export const BILLMATE_BILL_PAYMENT_CONFIG = buildProductManagementSimulation(billMateBillPaymentSuccessSpec);
export const CREDITEASE_LOAN_APPLICATION_CONFIG = buildProductManagementSimulation(creditEaseLoanCompletionSpec);
export const SAFEPAY_FRAUD_ALERT_CONFIG = buildProductManagementSimulation(safePayFraudAlertSpec);
export const SAVEWISE_SAVINGS_ACTIVATION_CONFIG = buildProductManagementSimulation(savewiseSavingsActivationSpec);
export const HELPPAY_SUPPORT_SELF_SERVICE_CONFIG = buildProductManagementSimulation(helpPaySelfServiceSpec);

export const FINTECH_PM_SIMULATIONS = [
    PAYLOOP_FIRST_TRANSACTION_CONFIG,
    VERICASH_KYC_CONFIG,
    SWIFTPAY_FAILED_TRANSFER_CONFIG,
    TRADEPAY_MERCHANT_ONBOARDING_CONFIG,
    FUNDLY_WALLET_FUNDING_CONFIG,
    BILLMATE_BILL_PAYMENT_CONFIG,
    CREDITEASE_LOAN_APPLICATION_CONFIG,
    SAFEPAY_FRAUD_ALERT_CONFIG,
    SAVEWISE_SAVINGS_ACTIVATION_CONFIG,
    HELPPAY_SUPPORT_SELF_SERVICE_CONFIG,
] as const;
