import { Header } from '../components/layout/Header';
import { Footer7 } from '../components/ui/footer-7';

const legalText = String.raw`WELCOME TO TURNVE TERMS AND CONDITIONS
 
1. By using TURNVE (referred to as "Our Services" or "Our Products"), YOU AGREE to these terms and any and incidental terms provided to you for Our Services that you use (collectively, "Terms"). Please read the Terms carefully, as they form your entire agreement with us.
2. USING THE SERVICES
1. Authority. YOU AGREE that you are permitted or allowed to use Our Services under applicable laws. If you are using Our Services on behalf of a company, business or other entity, you represent that you have the legitimate and legal authority to accept these Terms on behalf of that entity, in which case that entity accepts these Terms, and "you" means that entity. If you are accessing an account(s) on behalf of the account owner (e.g., as an administrator, consultant, analyst, educator, etc.), the Terms shall apply to your activities on behalf of the account owner.
2. Indemnity. If you are using Our Services on behalf of a company, business or other entity, or if you are using Our Services, you and the entity will hold harmless and indemnify TURNVE from any suit, claim or action arising from or related to the use of the Services or violation of these Terms, including any liability or expense arising from claims (including claims for negligence), losses, damages, suits, judgments, litigation costs and lawyers' fees.
3. Age. If you are under the Minimum Age of 18 years in Nigeria, you may not register for an account. Unless you have graduated from the university below the age majority and you must have told your parents about Our Service, and thereafter receives consent from both or either of your parents orally or otherwise to use Our Services, provided that consent to use Our Services BELOW THE Majority age was not obtained by fraud or misrepresentation. TURNVE will not be held responsible in whatever manner if you obtain funds from questionable source to open an account with TURNVE.
4. Member conduct. You agree not to use Our Services in any manner that violates these Terms (or assist, facilitate, or support others in doing so), including to:
a. obtain or attempt to obtain unauthorized access to the Services or to our servers, systems, network, or data;
b. make available any content or correspondence that is harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically, or otherwise objectionable;
c. violate any applicable laws or regulations;
d. impersonate any person or entity; or forge or manipulate headers or identifiers to disguise the origin of any content transmitted through Our Product;
e. Make available any content that you do not have the right to make available or that infringes any patent, trademark, trade secret, copyright or other proprietary rights of Our Products or any person or entity subscribed to Our Products;
f. post content containing advertisements or other commercial solicitations without our prior written permission (This clause is provided if there should be a user interactions either by text, or through any means, and whether users are going to see other users of Our Product in the app. If not the case, then this clause will be removed and some other similar clauses will be expunged)
g. make available viruses or any other computer code, files, programs or content designed to interrupt, destroy or limit the functionality of Our Products or affect other users, including but not limited to the use of any ad-blocking technology; or
h. interfere with or disrupt the Services or servers, systems or networks connected to the Services in any way.
i. access or collect data, or attempt to access or collect data, from our Product using any automated means, devices, programs, algorithms or methodologies, including but not limited to robots, spiders, scrapers, data mining tools, or data gathering or extraction tools, for any purpose without our express, prior permission.
j. use any material or content from, including without limitation any data, (a) to create any database, archive, mobile application, data feed, widget or any other aggregated data source that competes with or constitutes a material substitute for the Services, in whole or in part, offered on any of Our Services
k. or the services offered by our data providers, or (b) to provide any service that competes with or constitutes a material substitute for our Services or data offered by TURNVE or our data providers.
5. USE OF PRODUCTS. You must follow any guidelines or policies associated with the Services. You must not misuse or interfere with Our Products or try to access them using a method other than the interface and the instructions that we provide. You may use the Products only as permitted by law. Unless otherwise expressly stated, you may not access or reuse Our Product, or any portion thereof, for any commercial purpose.
6. Anti-Corruption Laws. You agree to comply with all applicable anti-corruption laws including laws that prohibit unlawful payments to anyone for a corrupt purpose in relation to these Terms.
7. Ownership and Reuse. Using the Services does not give you ownership of any intellectual or other property rights or interests in the Products or the content you access. You must not use any branding or logos used in the Services unless we have given you separate explicit written permission. You may not remove, obscure, or alter any legal notices displayed in or along with the Services. Unless you have explicit written permission, you must not reproduce, modify, rent, lease, sell, trade, distribute, transmit, broadcast, publicly perform, create derivative works based on, or exploit for any commercial purposes, any portion or use of, or access to, the Services (including content, advertisements, APIs, and software).
8. Software License. Subject to your continuing compliance with these Terms, we grant you a personal, royalty-free, non-transferable, non-assignable, revocable, and non-exclusive license to use the software and APIs we may provide to you as part of the Products. This license is for the sole purpose of enabling you to use and enjoy the benefit of the product we provide, in the manner permitted by these Terms and any additional terms or guidelines. You may not reverse engineer or attempt to extract the source code of our software, unless applicable laws prohibit those restrictions or you have our explicit written permission. Our software may automatically download and install security or other updates without prior notification to you.
9. Support. Unless otherwise expressly stated, we do not promise to provide you with any support for the Product. If we provide you with support, it is at our sole discretion and does not mean that we will continue to provide you with support in the future.
10. Fees. We reserve the right to charge fees for use of or access to Our Services (and any associated support), whether currently in existence or not, in our sole discretion. If we decide to charge fees, or anytime we charge fees, or when we charge fees, our payment terms will apply and we will provide you with prior notice or during your subscription for the use of Our Products.
11. Anti-abuse policy. We prohibit any form of misrepresentation using Our Products. You may not in connection with Our Products engage in commercial activity on non-commercial properties or apps or high volume activity without our prior written consent. You may not engage in conduct or activity that is disruptive to Our Product or the experience of other users.
12. Your Account; Notices
a. Account Information. You may need an account to use some Services. You must ensure that your account information (that is, the information you provided when you registered for or subscribed to Our Product) remains current, complete, accurate and truthful. Unless stated differently for you country or region in Section 14, all TURNVE accounts are non-transferable, and any rights to them terminate upon the account holder's death.
b. Access to Your Account. You are responsible for all activity that happens on or through your account. To protect your account, keep your password confidential. Do not reuse your account password with other services. Without prejudice to your statutory rights, if you forget your password and otherwise cannot validate your account to TURNVE, you acknowledge and agree that your account may be inaccessible to you and that all data associated with the account may not be retrievable, notwithstanding that we may have mechanisms in place to help you recover your account with TURNVE.
c. Notices. TURNE may provide you with notices, including service announcements and notices regarding changes to these Terms, by, but
d. not limited to, email, regular mail, text message or SMS, MMS, push notifications or in-app messages, postings on the Products, telephone, or other reasonable means now known or hereafter developed. You consent to receive these notices by any and all of the foregoing means. You may not receive notices if you violate the Terms by accessing the Product in an unauthorized manner, and you will be deemed to have received any and all notices that would have been delivered had you accessed Our Product in an authorized manner.
13. Privacy and Data Protection
Our Privacy Policy describes who we are, what information we collect from you, how we process your information, who we share it with, and your rights under data protection laws.

14. Procedure for Copyright or Other Intellectual Property Infringement Claims
We respect the intellectual property of others, and we expect our users to do the same for our Products. We may, in appropriate circumstances and at our discretion, disable, terminate, and/or take other appropriate steps relating to the accounts of users who may be infringers.

15. Content in the Services, License Grant to TURNVE and Consent to Use of AI
13. Content. Our Products may display some content that we did not create and do not own. This content is the sole responsibility of the entity or person that makes it available. We assume no responsibility for the conduct of third parties, including persons or entities with which you communicate using the Products. Many of the Services enable you to submit content. You - not TURNE - are entirely responsible for any content that you upload, post, email, transmit, or otherwise make available via the Product. We may remove and refuse to display content that violates the Terms or applicable laws or regulations, but that does not mean that we monitor the Products or review or screen any content. By using or accessing the Services you understand and agree that you may be exposed to offensive, indecent, or objectionable content.
14. Use of AI and Third-Party AI Providers. Some of Our Services have features and functionality powered by our trusted third-party AI providers ("AI Providers"). AI-powered chat service provided by Microsoft Copilot relies on search services from Bing. By utilizing our Services, you consent to sharing data that you provide to us, or that resides within your TURNVE account with our AI Providers for the purpose of enhancing features within our Our Products made available to you. In some instances, use of AI query features may be governed by the AI Provider's terms of service and privacy policy. You understand and agree that content or responses generated by AI may contain inaccuracies and should never be relied upon without independent verification. TURNVE does not control the content or responses provided by AI Providers, and makes no representations or warranties about the accuracy or completeness of such content or responses (or the sites and sources accessed through such content or responses). You also agree not to enter sensitive personal information into any AI powered query.
15. IP Ownership and License Grant. Except as otherwise provided in the specific product terms or guidelines for one of our Services, when you upload, share with or submit content to the Services you retain ownership of any intellectual property rights that you hold in that content and you grant to us a worldwide, royalty-free, non-exclusive, perpetual, irrevocable, transferable, sublicensable license to (a) use, host, store, reproduce, modify, prepare derivative works (such as translations, adaptations, summaries or other changes), communicate, publish, publicly perform, publicly display, and distribute this content in any manner, mode of delivery or media now known or developed in the future; and (b) permit other users to access, reproduce, distribute, publicly display, prepare derivative works of, and publicly perform your content via the Services, as may be permitted by the functionality of those Services (e.g., for users to re-blog, re-post or download your content). In some of the Services, there may be specific terms or settings allowing a different scope of use of the content submitted in those Services. You must have the necessary rights to grant us the license described for any content that you upload, share with or submit to Our Product.
16. Modifying and Terminating the Services; Terminating Accounts
16. We are constantly innovating, changing and improving Our Products. Unless stated differently, we may, without notice, add or remove functionalities or features, create new limits to Our Products, or temporarily or permanently suspend or stop a service.
17. You can stop using the Services at any time. You may cancel and delete your TURNVE account in the "Close Account" button provided for in Our Product, provided that you may be asked to provide the reason for your decision to close your account, of which, "Help Centre' option will be proffered to help resolve any issues you may have, but you still reserve your right to close your account with Our Products.
18. Subject to any statutory rights you might have, if your account is terminated, access to your username, password, and all related information, files, and content associated with your account may be terminated and your username may be recycled for use by others.
17. Our Warranties and Disclaimers
19. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WE, ALONG WITH OUR PARENT COMPANIES, SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AGENTS, PARTNERS, LICENSORS AND DISTRIBUTORS (COLLECTIVELY "TURNVE") DO NOT MAKE ANY REPRESENTATIONS, PROMISES, OR WARRANTIES, EXPRESS OR IMPLIED, ABOUT OUR PRODUCTS. WE PROVIDE OUR SERVICES "AS-IS," "WITH ALL FAULTS," AND "AS AVAILABLE." YOUR USE OF OUR SERVICES, INCLUDING CONTENT WITHIN THE SERVICES, IS AT YOUR OWN RISK AND WE DO NOT REPRESENT, PROMISE, OR WARRANT THAT OUR PRODUCTS WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE. YOU UNDERSTAND AND AGREE THAT NO DATA TRANSMISSION OVER THE INTERNET OR INFORMATION STORAGE TECHNOLOGY CAN BE GUARANTEED TO BE SECURE, AND WE EXPRESSLY DISCLAIM ANY WARRANTIES, EXPRESS OR IMPLIED, TO THAT EFFECT. WE MAKE NO COMMITMENTS, PROMISES OR WARRANTIES ABOUT THE CONTENT WITHIN OUR PRODUCTS OR CONTENT LINKED FROM OUR PRODUCTS, THE SUPPORT WE PROVIDE FOR THE SERVICES, THE SPECIFIC FUNCTIONS OF OUR PRODUCTS, THE SECURITY OF THE SERVICES, OR THE SERVICES' RELIABILITY, QUALITY, ACCURACY, AVAILABILITY, OR ABILITY TO MEET YOUR NEEDS, PROVIDE CERTAIN OUTPUTS OR ACHIEVE CERTAIN RESULTS.
20. SOME JURISDICTIONS PROVIDE FOR CERTAIN IMPLIED WARRANTIES, SUCH AS THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WE DISCLAIM ANY AND ALL IMPLIED OR EXPRESS PROMISES OR WARRANTIES ABOUT OUR PRODUCTS.
3. Limitation of Liability
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE AND UNDERSTAND THAT TURNVE WILL NOT BE LIABLE FOR: ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, TREBLE OR OTHER MULTIPLES OF DAMAGES, EXEMPLARY OR PUNITIVE DAMAGES ARISING FROM OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF THE SERVICES. TURNVE ARE NOT RESPONSIBLE FOR ANY LOST PROFITS, LOST REVENUES, LOST BUSINESS OPPORTUNITIES, DIMINUTION IN VALUE, INCLUDING ANY ALLEGED LOSS OR DIMINUTION IN VALUE OF PERSONAL INFORMATION, OR ANY OTHER LOSSES (COLLECTIVELY, "LOSSES") ARISING FROM OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF OR ACCESS TO THE SERVICES, INCLUDING, BUT NOT LIMITED TO, LOSSES RESULTING FROM OR IN CONNECTION WITH: THE DELETION OF, ALTERATION OF, MIS-DELIVERY OF, OR FAILURE TO STORE DATA MAINTAINED OR TRANSMITTED BY THE SERVICES; THE LIMITING, SUSPENSION OR TERMINATION OF YOUR ACCOUNT; YOUR DOWNLOADING OR SHARING OF INFORMATION, INCLUDING PERSONAL INFORMATION, VIA THE SERVICES; THE UNAUTHORIZED ACCESS TO YOUR ACCOUNT OR ANY DATA MAINTAINED OR TRANSMITTED BY THE SERVICES; LINKS PROVIDED BY THE SERVICES OR THIRD PARTIES TO EXTERNAL SITES OR RESOURCES; YOUR DEALINGS WITH OR PARTICIPATION IN PROMOTIONS OF ADVERTISERS FOUND ON OR THROUGH THE SERVICES; OR ANY GOODS OR SERVICES SOLD BY SUCH ADVERTISERS. TURNVE WILL NOT BE LIABLE FOR PROBLEMS CAUSED BY OTHERS, THE WRONGFUL OR UNLAWFUL ACTIONS OF THIRD PARTIES, OR AN ACT OF GOD. THE LIMITATIONS AND EXCLUSIONS IN THESE TERMS WILL APPLY WHETHER OR NOT WE HAVE BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY LOSSES ARISING.

4. TO THE FULLEST EXTENT PERMITTED BY LAW AND EXCEPT AS OTHERWISE STATED, TURNVE ARE NOT LIABLE IN CONNECTION WITH ANY DISPUTES THAT ARISE OUT OF OR RELATE TO THESE TERMS OR SERVICES FOR ANY AMOUNT GREATER THAN THE AMOUNT YOU PAID TO US FOR OUR SERVICES.
5. Feedback
You agree that any recommendation, idea, proposal, suggestion, feedback or other input ("Feedback") you submit to us related to our products, services, websites, apps, or technology may be used by us without any notice, obligation, restriction, reimbursement or compensation to you and you waive (or agree not to enforce) any and all rights that may now or in the future exist (including moral and equivalent rights) in any Feedback.

18. Fee-Based Services and Billing.
Unless otherwise specified in the additional terms that apply to Our Services you are using, the terms in this Section 18 apply to you.

1. We offer products and subscriptions for a fee ("fee-based Services"). These fee-based Services are governed by the additional terms you agree to when you register for the fee-based Service and these Terms. If you register for a fee-based Service, you must designate a payment method and provide us with accurate billing and payment information and you have the continuing obligation to keep it up to date. Many fee-based Services may require you to have, or register for,TURNE ID .
1. The following important provisions apply to all of our fee-based Services:
a. Third-Party products. If the fee-based Service includes a third-party product, you understand and agree that your purchase and use of that service is also subject to the third party's terms of service and privacy policy, which you should read thoroughly before agreeing to them.
b. Payments. You represent that you are at least the minimum age required to enter into a legal agreement. You agree to pay us for any fee-based Services you purchase from us, as well as all other charges incurred under your account, including applicable taxes and fees. You are responsible for all charges incurred under your account, including purchases made by you or anyone you allow to use your account or any sub-or linked accounts (including any person with implied, actual, or apparent authority) or anyone who gains access to your account as a result of your failure to safeguard your authentication credentials.
c. Payment Methods. You authorize and direct us to charge your designated payment method for these charges or, if it fails, to charge any other payment method you have on file with us, even if we received it in association with other fee-based services. You are responsible for all charges even if your payment method fails or is denied. You authorize and direct us to retain all information about any subscription or payment method(s) associated with your account. We may import payment information that you entered during a prior purchase and provide you with the option to use that payment information during purchase of a new product. You permit us to obtain and use updated information from the issuer of your payment method in accordance with the policies and procedures of any applicable card brands. We may in some instances continue charging a payment method past its expiration date at our discretion and subject to the payment processors' or issuing bank's approval. Surcharges may apply if you use certain payment methods, such as payment from your savings account.
d. Payment Terms. We may charge for fee-based Services in advance and on a daily, monthly, yearly, lump sum, or other basis in accordance with the stated terms, as long as your subscription remains active, even if you have not downloaded or used the Service or accessed your online account.
e. Auto-Renewal. We use auto-renewal for many of our fee-based Services. At the expiration of each subscription term for such fee-based Services, we will automatically renew your subscription and charge the credit card or other payment method you have provided to us, unless you cancel your subscription at least 48 hours before the end of the current period. Your subscription will be automatically renewed at the then-current price, excluding promotional and discount pricing. We may, in our sole discretion, post charges to your payment method individually or aggregate charges for some or all of your fee-based Services with us.
f. Fraud Protection. We may take steps to verify the validity of the credit or debit card information you provide to us. You authorize us to do so for verification and anti-fraud purposes.
g. Free Trials. We may offer you free trials, so that you may try a fee-based Service subscription without charge or obligation ("Free Trial"). Unless otherwise stated and unless you cancel your subscription prior to the expiration of the Free Trial, periodic subscription fees will be charged at the then-applicable rate upon expiration of the Free Trial period and will continue to be charged until the subscription is canceled. If you are not satisfied with a particular fee-based Service, you must cancel the subscription before the Free Trial ends to avoid charges. We reserve the right to limit you to one Free Trial or promotion of a fee-based Service and to prohibit the combining of Free Trials or other promotional offers.
h. No Refunds. All charges are nonrefundable unless provided otherwise in the terms you agree to when you register for a fee-based Service, unless stated differently for your country or region.
i. Termination. We, in our sole discretion, may change, discontinue or terminate any or all aspects of a fee-based Service without notice, including access to support services, content and other products or services ancillary to the fee-based Service, subject to providing an appropriate refund for any portions of a specified but no longer available term. You may cancel a fee-based Service at any time by logging into your online account and terminating the subscription.
j. Change in Fees and Billing Method. We may change our fees and billing methods at any time. We will provide you with notice of any price increase at least thirty (30) days in advance. Subject to applicable law, (i) if you disagree with any proposed change, your sole remedy is to cancel your fee-based Service before the price change takes effect and (ii) your continued use of or subscription to the Service after the price change takes effect constitutes your agreement to pay the new price for the Service.
k. Delinquency. After 30 days from the date of any unpaid charges, your fee-based Service will be deemed delinquent and we may terminate or suspend your account and fee-based Service for nonpayment. You are liable for any fees, including attorney and collection fees, incurred by us in our efforts to collect any remaining balances from you.
l. 90-Day Notice Period. You must notify us about any billing problems or discrepancies within 90 days after they first appear on your billing method statement. If you do not bring them to our attention within 90 days, you agree that you waive your right to dispute such problems or discrepancies.
19. About these Terms
2. Third Party Beneficiaries and Conflicts. These Terms control the relationship between you and us. They do not create any third party beneficiary rights. If there is a conflict or inconsistency between the terms in this document and the additional terms associated with a particular Service, the additional terms will control solely for that conflict or inconsistency.
3. Modification of the Terms. We may modify the Terms from time to time. Unless we indicate otherwise, modifications will be effective as of the date they are posted on this page or any successor page. You should look at the Terms regularly. We will provide notice of material modifications.
4. Continued Use of the Services. You may stop using the Services at any time, but your continued use of or subscription to a Service after the effective date of any modifications to the Terms means that you agree to the Terms as modified.
5. Waiver and Severability of Terms. Our failure to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision. If any provision (or part of a provision) of these Terms is found to be invalid, you and we nevertheless agree to give effect to the intentions as reflected in the provision, and the other provisions of these Terms remain in full force and effect.
6. Assignment by Us. We may freely assign these Terms and all of the policies and other documents incorporated or referenced in it (including all rights, licenses, and obligations under it or them), in whole or in part and without notice, for any reason, including for the purpose of internal restructuring (for example, partnership, mergers or liquidations).
20 BINDING ARBITRATION AGREEMENT. YOU AND US BOTH AGREE TO RESOLVE ANY AND ALL DISPUTES, CONTROVERSIES OR CLAIMS THAT IN ANY WAY ARISE OUT OF OR RELATE TO THESE TERMS OR FROM ANY SERVICES YOU RECEIVE FROM US (OR FROM ANY ADVERTISING FOR ANY SUCH SERVICES), INCLUDING ANY DISPUTES BETWEEN YOU AND OUR EMPLOYEES OR AGENTS ("DISPUTE(S)"), ONLY BY ARBITRATION ON AN INDIVIDUAL BASIS. THIS INCLUDES BUT IS NOT LIMITED TO ANY CLAIM THAT ALL OR ANY PART OF THIS ARBITRATION AGREEMENT IS VOID OR VOIDABLE, WHETHER A CLAIM IS SUBJECT TO ARBITRATION, AND ANY DISPUTE REGARDING THE PAYMENT OF ADMINISTRATIVE OR ARBITRATOR FEES. YOU UNDERSTAND THAT BY AGREEING TO THESE TERMS, ARBITRATION WILL BE THE SOLE AND EXCLUSIVE MEANS OF RESOLVING ANY DISPUTE BETWEEN US. YOU ALSO UNDERSTAND THAT BY AGREEING TO THESE TERMS, YOU AND WE ARE GIVING UP THE RIGHT TO BRING A CLAIM IN COURT AND THAT YOU AND WE ARE GIVING UP THE RIGHT TO PROCEED WITH ANY CLASS ACTION OR OTHER REPRESENTATIVE ACTION. We also both agree that:
a. Informal Dispute Resolution. If either you or we intend to arbitrate a Dispute under these Terms, the party seeking arbitration must first notify the other party of the Dispute in writing at least 60 days in advance of initiating the arbitration. Notice to us should be sent either by mail to TURNVE, Attn: (registered address/head office of Turne should be here); or (official email address of TURNE here) Notice to you will be to your email address(es) or street address(es), if any, that we have in our records at the time the notice is sent. The written description must be on an individual basis and provide, at minimum, the following information: the sender's name; a description of the nature or basis of the claim or Dispute; the specific relief sought; and, if you are a TURNVE registered user, your TURNVE ID or TURNVE email address. After receipt of the written description by TURNVE, you and TURNVE agree to personally meet and confer, via telephone or videoconference, to attempt to resolve the Dispute. If a party is represented by counsel, that party's counsel may participate in the conference, but the party themselves shall also personally attend the conference.

b. If we are unable to resolve the Dispute within 60 days, either party may then proceed to file a claim for arbitration in accordance with the Dispute resolution provisions below.

c. The aforementioned Informal Dispute Resolution process, including the written description and personal participation in the meet and confer, is a prerequisite and condition precedent to commencing any formal Dispute resolution proceeding. The parties agree that any relevant limitations period and filing fees or other deadlines will be tolled while the parties engage in this Informal Dispute Resolution process. The parties further agree that whether a complaining party has satisfied these Informal Dispute Resolution procedures, including whether the written description contained all required information, is an issue that can be decided by a court as a prerequisite to arbitration.

d. Arbitration Procedure. The Arbitration and Mediation Act (AMA) 2023, in the Federal Republic of Nigeria, shall apply to these Terms. Any and all Disputes will be resolved by arbitration before a sole arbitrator agreed by both parties by and administered in accordance with the arbitration rules and regulations in Nigeria, including, as applicable, any dispute resolution rules and procedures that will lead to the best possible resolution between the parties. If you are initiating arbitration, a copy of the demand shall also be emailed to (Official TURNVE email here). If you are a registered TURNVE user, any demand initiating arbitration, whether filed by you or TURNVE, must include your TURNVE ID or TURNVE email address. If TURNVE is initiating arbitration, a copy of the demand shall also be sent to the email address(es) or street address(es), if any, that we have in our records at the time the arbitration is initiated.

e. Unless otherwise prohibited by law, all arbitration proceedings will be confidential and closed to the public and any parties other than you and TURNVE (and each of the parties' authorized representatives and agents), and all records relating thereto will be permanently sealed, except as necessary to obtain court confirmation of the arbitration award (provided that the party seeking confirmation shall seek to file such records under seal to the extent permitted by law).

e. High Court Option. As an alternative to arbitration, either party may elect to have any claims resolved in High Court in Nigeria where the registered office address of TURNVE is situate, provided that arbitration procedures in these TERMS have been exhausted.
f. 30-Day Right to Opt Out. You have the right to opt out and not be bound by the Arbitration Agreement by sending written notice of your decision to opt out to (provide official TURNVE email here) with the subject line, "ARBITRATION OPT-OUT". To be valid, the notice must be sent on an individual basis within thirty (30) days of (a) you first agreeing to the version of these Terms dated 1 January, 2026, or later; or (b) you first using the Services, whichever is later. Any prior valid opt-out of a requirement to arbitrate disputes with TURNVE will continue to apply. Otherwise, you shall be bound to arbitrate disputes in accordance with the Arbitration Agreement. If you opt out of the Arbitration Agreement, you may exercise your right to a trial by judge, as permitted by applicable law, but any prior existing agreement to arbitrate disputes under a prior version of the Arbitration Agreement will not apply to claims not yet filed. If you opt out of the Arbitration Agreement, TURNVE also will not be bound by it.
e. TURNVE reserves the right to make changes to this section. Any such changes will go into effect after 30 days and apply to all claims not yet filed regardless of when such claims may have accrued. If TURNVE changes this section after the date you first accepted this Arbitration Agreement (or accepted any subsequent changes to this Arbitration Agreement), you agree that your continued use of the Service 30 days after such change will be deemed acceptance of those changes.
f. Severability. If any part of this agreement to arbitrate is found by a court of competent jurisdiction to be unenforceable, the court will reform the agreement to the extent necessary to cure the unenforceable part(s), and the parties will arbitrate their Dispute(s) without reference to or reliance upon the unenforceable part(s).
g. Choice of Law. These Terms and the relationship between the parties, including any claim or dispute that might arise between the parties, whether sounding in contract, tort, or otherwise, will be governed by the laws of Federal Republic of Nigeria without regard to its conflict of law provisions. In no event will the parties bring claims against one another under the laws of another jurisdiction.
h. Forum. Except for small claims matters, if for any reason a Dispute proceeds in court rather than through arbitration, all such Disputes (regardless of theory) arising out of or relating to these Terms, or the relationship between you and us, will be brought exclusively in the High Court of the State where the registered office is situate or in the High Court of the State where the affected subscriber reside. In such cases, you and we agree to submit to the personal jurisdiction of the states courts.
 
1`;

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-24">
        <section className="border-b border-border bg-secondary/30 py-16">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
            <p className="mb-3 text-sm font-semibold uppercase tracking-widest text-primary">
              Legal
            </p>
            <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
              Privacy Policy and Terms
            </h1>
            <p className="mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground">
              The terms below apply to TURNVE services and products.
            </p>
          </div>
        </section>

        <section className="py-12">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
            <article className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-8">
              <pre className="whitespace-pre-wrap break-words font-sans text-sm leading-7 text-muted-foreground">
                {legalText}
              </pre>
            </article>
          </div>
        </section>
      </main>

      <Footer7
        logo={{ url: '/', src: '/logo.png', alt: 'TURNVE logo', title: 'TURNVE' }}
        sections={[
          {
            title: 'Product',
            links: [
              { name: 'Features', href: '/features' },
              { name: 'Programs', href: '/programs' },
              { name: 'Pricing', href: '/pricing' },
            ],
          },
          {
            title: 'Company',
            links: [
              { name: 'About Us', href: '/about' },
              { name: 'Blog', href: '/blog' },
              { name: 'Contact', href: '/contact' },
            ],
          },
          {
            title: 'Resources',
            links: [
              { name: 'FAQ', href: '/faq' },
              { name: 'Developers', href: '/developers' },
            ],
          },
        ]}
        description="AI-powered practical career platform helping professionals gain management experience, build portfolios, and land managerial roles."
        socialLinks={[]}
        copyright="© 2026 TURNVE. All rights reserved."
        legalLinks={[{ name: 'Privacy & Terms', href: '/privacy' }]}
      />
    </div>
  );
}
